#!/bin/bash

myhostname=$(hostname)
mydate=$(date)

cat <<EOF
System Report for $myhostname generated by $USER, on $mydate
 
System Information
------------------
OS: DISTRO NAME AND VERSION
Uptime: UPTIME
CPU: PROCESSOR MAKE AND MODEL
RAM: SIZE OF INSTALLED RAM
Disk(s): MAKE AND MODEL AND SIZE FOR ALL INSTALLED DISKS
Video: MAKE AND MODEL OF VIDEO CARD
Host Address: IP ADDRESS FOR THE INTERFACE THAT IS CONNECTED TO THE DEFAULT GATEWAY
Gateway IP: DEFAULT GATEWAY ADDRESS
DNS Server: IP OF DNS SERVER
 
System Status
-------------
Users Logged In: USER,USER,USER...
Disk Space: FREE SPACE FOR LOCAL FILESYSTEMS IN FORMAT: /MOUNTPOINT N
Process Count: N
Load Averages: N, N, N
Listening Network Ports: N, N, N, ...
UFW Status: UFWSTATUS
EOF

